#!/bin/bash

build() {
    add_binary "/usr/bin/dols" "/usr/bin/dols"

    add_systemd_unit 'dols.service'

    map add_file \
        '/etc/ssh/ssh_host_rsa_key' \
        '/etc/ssh/ssh_host_ecdsa_key' \
        '/etc/passwd' \
        '/etc/shadow' \
        '/etc/dols.toml'

    add_checked_modules '/drivers/net/'
}

help() {
    cat << HELPEOF
Hello, World!
HELPEOF
}
